# Generated by Django 2.2.5 on 2019-10-22 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='like',
            new_name='likes',
        ),
    ]
