# Generated by Django 2.2.5 on 2019-10-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_auto_20191015_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['photo', 'bio']},
        ),
    ]
