# Generated by Django 2.2.5 on 2019-10-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_image_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(default='images/default.jpeg', upload_to='images/'),
        ),
    ]
