# Generated by Django 2.2.5 on 2019-10-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_auto_20191016_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('comments', models.TextField()),
            ],
        ),
    ]
